# Generated by Django 4.2.1 on 2024-04-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_women_m_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='m_count',
        ),
        migrations.AddField(
            model_name='husband',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
